module.exports = [
  {
    categoryName: 'Coats',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/coats?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Coats'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Coats',
  },
  {
    categoryName: 'Dresses',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/dresses?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Dresses'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Dresses',
  },
  {
    categoryName: 'Gowns',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/gowns?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Gowns'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Gowns',
  },
  {
    categoryName: 'Jackets',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/jackets?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Jackets'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Jackets',
  },
  {
    categoryName: 'Jeans',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/jeans?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Jeans'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Jeans',
  },
  {
    categoryName: 'Jumpsuits',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/jumpsuits?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Jumpsuits'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Jumpsuits',
  },
  {
    categoryName: 'Knitwear',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/knitwear?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Knitwear'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Knitwear',
  },
  {
    categoryName: 'Lingerie',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/lingerie?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Lingerie'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Lingerie',
  },
  {
    categoryName: 'Nightwear',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/nightwear?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Nightwear'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Nightwear',
  },
  {
    categoryName: 'Shorts',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/shorts?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Shorts'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Shorts',
  },
  {
    categoryName: 'Ski Wear',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/ski-wear?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Ski Wear'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Ski Wear',
  },
  {
    categoryName: 'Skirts',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/skirts?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Skirts'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Skirts',
  },
  {
    categoryName: 'Sportswear',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/sportswear?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Sportswear'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Sportswear',
  },
  {
    categoryName: 'Sweatshirts',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/sweatshirts?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Sweatshirts'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Sweatshirts',
  },
  {
    categoryName: 'Swinwear',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/swimwear?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Swinwear'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Swinwear',
  },
  {
    categoryName: 'Tops',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/tops?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Tops'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Tops',
  },
  {
    categoryName: 'Trousers',
    categoryUrl: 'https://www.harrods.com/en-gb/women/clothing/trousers?view=Product&list=Grid&viewAll=False&pageNumber=',
    tags: ['Trousers'],
    type: 'Designer Womenswear',
    googleproductcategory: 'Women Trousers',
  },
];
